//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarEvents.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CalEventLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalEventLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalendarEvents.Resources.Languages.CalEventLang", typeof(CalEventLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days +/- end date:.
        /// </summary>
        internal static string AddDaysToEnd_Text {
            get {
                return ResourceManager.GetString("AddDaysToEnd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days +/- start date:.
        /// </summary>
        internal static string AddDaysToStart_Text {
            get {
                return ResourceManager.GetString("AddDaysToStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string Agree_Text {
            get {
                return ResourceManager.GetString("Agree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All calendars.
        /// </summary>
        internal static string AllCalendars_Text {
            get {
                return ResourceManager.GetString("AllCalendars_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonClose_Text {
            get {
                return ResourceManager.GetString("ButtonClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ButtonShare_Text {
            get {
                return ResourceManager.GetString("ButtonShare_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar:.
        /// </summary>
        internal static string Calendar_Text {
            get {
                return ResourceManager.GetString("Calendar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If permission to the calendar is not given, permission can be enabled in the device settings, select the application and grant access to the calendar..
        /// </summary>
        internal static string CalendarPermission_Text {
            get {
                return ResourceManager.GetString("CalendarPermission_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendars:.
        /// </summary>
        internal static string Calendars_Text {
            get {
                return ResourceManager.GetString("Calendars_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Clear_Text {
            get {
                return ResourceManager.GetString("Clear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the application..
        /// </summary>
        internal static string CloseApplication_Text {
            get {
                return ResourceManager.GetString("CloseApplication_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        internal static string Contact_Text {
            get {
                return ResourceManager.GetString("Contact_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Copyright_Text {
            get {
                return ResourceManager.GetString("Copyright_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash and error reports: To help us fixing any problems, the application will send anonymous crash and error reports when the application is restarted.
        ///The reports contain information on the crash or error, including device specifications, operating system, application version, timestamp, and anonymous installation identifier.
        ///The data is collected for the sole purpose of helping us to improve the application and does not include any personal information.  No other data is collected.
        ///Anonymous crash and  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CrashErrorReport_Text {
            get {
                return ResourceManager.GetString("CrashErrorReport_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark_Text {
            get {
                return ResourceManager.GetString("Dark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date:.
        /// </summary>
        internal static string DateEnd_Text {
            get {
                return ResourceManager.GetString("DateEnd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format:.
        /// </summary>
        internal static string DateFormat_Text {
            get {
                return ResourceManager.GetString("DateFormat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System long.
        /// </summary>
        internal static string DateFormatSystemLong_Text {
            get {
                return ResourceManager.GetString("DateFormatSystemLong_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System short.
        /// </summary>
        internal static string DateFormatSystemShort_Text {
            get {
                return ResourceManager.GetString("DateFormatSystemShort_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO 8601.
        /// </summary>
        internal static string DateISO8601_Text {
            get {
                return ResourceManager.GetString("DateISO8601_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        internal static string DateStart_Text {
            get {
                return ResourceManager.GetString("DateStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default_Text {
            get {
                return ResourceManager.GetString("Default_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve and share calendar events.
        /// </summary>
        internal static string Description_Text {
            get {
                return ResourceManager.GetString("Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disagree.
        /// </summary>
        internal static string Disagree_Text {
            get {
                return ResourceManager.GetString("Disagree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string Email_Text {
            get {
                return ResourceManager.GetString("Email_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device contains a calendar that contains one or more errors or is not compatible with this application..
        /// </summary>
        internal static string ErrorCalendar_Text {
            get {
                return ResourceManager.GetString("ErrorCalendar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date must be equal to or greater than the start date..
        /// </summary>
        internal static string ErrorDate_Text {
            get {
                return ResourceManager.GetString("ErrorDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle_Text {
            get {
                return ResourceManager.GetString("ErrorTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear events.
        /// </summary>
        internal static string EventsClear_Text {
            get {
                return ResourceManager.GetString("EventsClear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy events.
        /// </summary>
        internal static string EventsCopy_Text {
            get {
                return ResourceManager.GetString("EventsCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve events.
        /// </summary>
        internal static string EventsGet_Text {
            get {
                return ResourceManager.GetString("EventsGet_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share events.
        /// </summary>
        internal static string EventsShare_Text {
            get {
                return ResourceManager.GetString("EventsShare_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Info_Text {
            get {
                return ResourceManager.GetString("Info_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date format can be changed in the settings to the international standard format ISO 8601 (YYYY-MM-DD).
        ///Note: 4 years is the maximum period an iOS calendar can search for events.
        ///
        ///Google Translate was used for the translation of the text. This is not a guarantee that all translations are correct.
        ///The supporting languages are: Czech, Danish, Dutch, English, Finnish, French, German, Hungarian, Italian, Norwegian, Polish, Portuguese, Romanian, Spanish and Swedish.
        ///
        ///You can always contact me for any co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoExplanation_Text {
            get {
                return ResourceManager.GetString("InfoExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language_Text {
            get {
                return ResourceManager.GetString("Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application may be used freely for non-commercial purposes.
        ///Use this program entirely at your own risk..
        /// </summary>
        internal static string License_Text {
            get {
                return ResourceManager.GetString("License_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you agree with the license conditions?.
        /// </summary>
        internal static string LicenseAgreement_Text {
            get {
                return ResourceManager.GetString("LicenseAgreement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string LicenseMit_Text {
            get {
                return ResourceManager.GetString("LicenseMit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software is provided &apos;as is&apos;, without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the author and/or publisher be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software..
        /// </summary>
        internal static string LicenseMit2_Text {
            get {
                return ResourceManager.GetString("LicenseMit2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string LicenseTitle_Text {
            get {
                return ResourceManager.GetString("LicenseTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light_Text {
            get {
                return ResourceManager.GetString("Light_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always send.
        /// </summary>
        internal static string LogAlwaysSend_Text {
            get {
                return ResourceManager.GetString("LogAlwaysSend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t send.
        /// </summary>
        internal static string LogDontSend_Text {
            get {
                return ResourceManager.GetString("LogDontSend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application detected an error in a previous session.
        ///To improve the application, I would like to receive the log with that error.
        ///May the log of that error be sent?
        ///Thank you in advance..
        /// </summary>
        internal static string LogMessage_Text {
            get {
                return ResourceManager.GetString("LogMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string LogSend_Text {
            get {
                return ResourceManager.GetString("LogSend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the error log.
        /// </summary>
        internal static string LogTitle_Text {
            get {
                return ResourceManager.GetString("LogTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been detected. Send the error log?.
        /// </summary>
        internal static string LogTitle2_Text {
            get {
                return ResourceManager.GetString("LogTitle2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Events.
        /// </summary>
        internal static string NameProgram_Text {
            get {
                return ResourceManager.GetString("NameProgram_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Events.
        /// </summary>
        internal static string NameProgramLocal_Text {
            get {
                return ResourceManager.GetString("NameProgramLocal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No_Text {
            get {
                return ResourceManager.GetString("No_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No personal and other data is stored or passed on to myself and others..
        /// </summary>
        internal static string PrivacyPolicy_Text {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy:.
        /// </summary>
        internal static string PrivacyPolicyTitle_Text {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset_Text {
            get {
                return ResourceManager.GetString("Reset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save_Text {
            get {
                return ResourceManager.GetString("Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for:.
        /// </summary>
        internal static string SearchFor_Text {
            get {
                return ResourceManager.GetString("SearchFor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Text {
            get {
                return ResourceManager.GetString("Settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changed settings must be saved in order to apply them..
        /// </summary>
        internal static string SettingsSaved_Text {
            get {
                return ResourceManager.GetString("SettingsSaved_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System_Text {
            get {
                return ResourceManager.GetString("System_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string Theme_Text {
            get {
                return ResourceManager.GetString("Theme_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between the ISO date format and the system date format.
        /// </summary>
        internal static string ToolTipDateFormat_Text {
            get {
                return ResourceManager.GetString("ToolTipDateFormat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear calendar events.
        /// </summary>
        internal static string ToolTipEventsClear_Text {
            get {
                return ResourceManager.GetString("ToolTipEventsClear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy calendar events to the clipboard.
        /// </summary>
        internal static string ToolTipEventsCopy_Text {
            get {
                return ResourceManager.GetString("ToolTipEventsCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve calendar events.
        /// </summary>
        internal static string ToolTipEventsGet_Text {
            get {
                return ResourceManager.GetString("ToolTipEventsGet_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share calendar events.
        /// </summary>
        internal static string ToolTipEventsShare_Text {
            get {
                return ResourceManager.GetString("ToolTipEventsShare_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string ToolTipGoBack_Text {
            get {
                return ResourceManager.GetString("ToolTipGoBack_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward.
        /// </summary>
        internal static string ToolTipGoForward_Text {
            get {
                return ResourceManager.GetString("ToolTipGoForward_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for text in the title or leave this field blank.
        /// </summary>
        internal static string ToolTipSearchFor_Text {
            get {
                return ResourceManager.GetString("ToolTipSearchFor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the settings to their default values.
        /// </summary>
        internal static string ToolTipSettingsReset_Text {
            get {
                return ResourceManager.GetString("ToolTipSettingsReset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the settings.
        /// </summary>
        internal static string ToolTipSettingsSave_Text {
            get {
                return ResourceManager.GetString("ToolTipSettingsSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version_Text {
            get {
                return ResourceManager.GetString("Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website_Text {
            get {
                return ResourceManager.GetString("Website_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes_Text {
            get {
                return ResourceManager.GetString("Yes_Text", resourceCulture);
            }
        }
    }
}
