//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarEvents.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CalEventLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalEventLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalendarEvents.Resources.Languages.CalEventLang", typeof(CalEventLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string Agree_Text {
            get {
                return ResourceManager.GetString("Agree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonClose_Text {
            get {
                return ResourceManager.GetString("ButtonClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ButtonShare_Text {
            get {
                return ResourceManager.GetString("ButtonShare_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendars:.
        /// </summary>
        internal static string Calendars_Text {
            get {
                return ResourceManager.GetString("Calendars_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Clear_Text {
            get {
                return ResourceManager.GetString("Clear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the application..
        /// </summary>
        internal static string CloseApplication_Text {
            get {
                return ResourceManager.GetString("CloseApplication_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        internal static string Contact_Text {
            get {
                return ResourceManager.GetString("Contact_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Copyright_Text {
            get {
                return ResourceManager.GetString("Copyright_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark_Text {
            get {
                return ResourceManager.GetString("Dark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format:.
        /// </summary>
        internal static string DateFormat_Text {
            get {
                return ResourceManager.GetString("DateFormat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO 8601.
        /// </summary>
        internal static string DateISO8601_Text {
            get {
                return ResourceManager.GetString("DateISO8601_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default_Text {
            get {
                return ResourceManager.GetString("Default_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get and share calendar events.
        /// </summary>
        internal static string Description_Text {
            get {
                return ResourceManager.GetString("Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disagree.
        /// </summary>
        internal static string Disagree_Text {
            get {
                return ResourceManager.GetString("Disagree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string Email_Text {
            get {
                return ResourceManager.GetString("Email_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle_Text {
            get {
                return ResourceManager.GetString("ErrorTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear events.
        /// </summary>
        internal static string EventsClear_Text {
            get {
                return ResourceManager.GetString("EventsClear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy events.
        /// </summary>
        internal static string EventsCopy_Text {
            get {
                return ResourceManager.GetString("EventsCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get events.
        /// </summary>
        internal static string EventsGet_Text {
            get {
                return ResourceManager.GetString("EventsGet_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share events.
        /// </summary>
        internal static string EventsShare_Text {
            get {
                return ResourceManager.GetString("EventsShare_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Info_Text {
            get {
                return ResourceManager.GetString("Info_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date format can be changed in the settings to the international standard format ISO 8601 (YYYY-MM-DD).
        ///
        ///Google Translate was used for the translation of the text. This is not a guarantee that all translations are correct.
        ///The supporting languages are: Czech, Danish, Dutch, English, Finnish, French, German, Hungarian, Italian, Norwegian, Polish, Portuguese, Romanian, Spanish and Swedish.
        ///
        ///You can always contact me for any corrections..
        /// </summary>
        internal static string InfoExplanation_Text {
            get {
                return ResourceManager.GetString("InfoExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language_Text {
            get {
                return ResourceManager.GetString("Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application may be used freely for non-commercial purposes.
        ///Use this program entirely at your own risk..
        /// </summary>
        internal static string License_Text {
            get {
                return ResourceManager.GetString("License_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you agree with the license conditions?.
        /// </summary>
        internal static string LicenseAgreement_Text {
            get {
                return ResourceManager.GetString("LicenseAgreement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string LicenseMit_Text {
            get {
                return ResourceManager.GetString("LicenseMit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software is provided &apos;as is&apos;, without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the author and/or publisher be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software..
        /// </summary>
        internal static string LicenseMit2_Text {
            get {
                return ResourceManager.GetString("LicenseMit2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string LicenseTitle_Text {
            get {
                return ResourceManager.GetString("LicenseTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light_Text {
            get {
                return ResourceManager.GetString("Light_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Events.
        /// </summary>
        internal static string NameProgram_Text {
            get {
                return ResourceManager.GetString("NameProgram_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No_Text {
            get {
                return ResourceManager.GetString("No_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days in the future:.
        /// </summary>
        internal static string NumDaysFuture_Text {
            get {
                return ResourceManager.GetString("NumDaysFuture_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days in the past:.
        /// </summary>
        internal static string NumDaysPast_Text {
            get {
                return ResourceManager.GetString("NumDaysPast_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No personal and other data is stored or passed on to myself and others..
        /// </summary>
        internal static string PrivacyPolicy_Text {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy:.
        /// </summary>
        internal static string PrivacyPolicyTitle_Text {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Events.
        /// </summary>
        internal static string ProgramName_Text {
            get {
                return ResourceManager.GetString("ProgramName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset_Text {
            get {
                return ResourceManager.GetString("Reset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save_Text {
            get {
                return ResourceManager.GetString("Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for:.
        /// </summary>
        internal static string SearchFor_Text {
            get {
                return ResourceManager.GetString("SearchFor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Text {
            get {
                return ResourceManager.GetString("Settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changed settings must be saved in order to apply them..
        /// </summary>
        internal static string SettingsSaved_Text {
            get {
                return ResourceManager.GetString("SettingsSaved_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System_Text {
            get {
                return ResourceManager.GetString("System_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string Theme_Text {
            get {
                return ResourceManager.GetString("Theme_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between the ISO date format and the system date format.
        /// </summary>
        internal static string ToolTipDateFormat_Text {
            get {
                return ResourceManager.GetString("ToolTipDateFormat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string ToolTipGoBack_Text {
            get {
                return ResourceManager.GetString("ToolTipGoBack_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward.
        /// </summary>
        internal static string ToolTipGoForward_Text {
            get {
                return ResourceManager.GetString("ToolTipGoForward_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version_Text {
            get {
                return ResourceManager.GetString("Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website_Text {
            get {
                return ResourceManager.GetString("Website_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes_Text {
            get {
                return ResourceManager.GetString("Yes_Text", resourceCulture);
            }
        }
    }
}
